/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

    about: [
        'about/about-contribute',
        'about/about-events',
        'about/about-meetings',
        'about/about-news',
        'about/about-releases',
        'about/about-resources',
    ],
    getting_started: [
        'getting_started/getting_started-getting-started',
        'getting_started/getting_started-software-identification',
        'getting_started/getting_started-security',
        'getting_started/getting_started-compliance',
    ],
};

export default sidebars;
