/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

    about: [
        'about/about-aboutcode-foundation',
        'about/about-contribute',
        'about/about-resources',
        'about/about-news',
        'about/about-events',
        'about/about-history',
    ],

    dejacode: [
        'dejacode/dejacode-welcome',
        'dejacode/dejacode-getting-started',
        'dejacode/dejacode-capabilities',
        'dejacode/dejacode-explore-dejacode',
        'dejacode/dejacode-cravex',
        'dejacode/dejacode-documentation',
    ],

    purldb: [
        'purldb/purldb-welcome',
        'purldb/purldb-getting-started',
        'purldb/purldb-packageurl-spec',
        'purldb/purldb-purldb-service',
        'purldb/purldb-documentation',
    ],

    scancode: [
        'scancode/scancode-welcome',
        'scancode/scancode-getting-started',
        'scancode/scancode-capabilities',
        'scancode/scancode-documentation',
    ],

    vulnerablecode: [
        'vulnerablecode/vulnerablecode-welcome',
        'vulnerablecode/vulnerablecode-getting-started',
        'vulnerablecode/vulnerablecode-capabilities',
        'vulnerablecode/vulnerablecode-vcio-service',
        'vulnerablecode/vulnerablecode-documentation',
    ],

};

export default sidebars;
